config:
  githubUrl: https://api.github.com/graphql # change if you use GH enterprise
  githubToken: xxx # GH personal access token

  userList: # GH user list
    - yyy
    - zzz

  sprintList: # define your sprints here
    - title: Sprint 44
      duration: 2020-09-29..2020-10-12
    - title: Sprint 45
      duration: 2020-10-13..2020-10-26
    - title: Sprint 46
      duration: 2020-10-27..2020-11-9

  bugLabel: label:Bug # customize your bug label

server:
  port: 8013
