config:
  githubUrl: https://api.github.com/graphql # change if you use GH enterprise
  githubToken: zzz # GH personal access token

  userList: # GH username list
    - wisnup
    - zzz

  sprintList: # define your sprints here
#    - title: Sprint 43 # H1 2020
#      duration: 2020-09-15..2020-09-28
    - title: Sprint 44
      duration: 2020-09-29..2020-10-12
    - title: Sprint 45
      duration: 2020-10-13..2020-11-02
    - title: Sprint 46
      duration: 2020-11-03..2020-11-23
    - title: Sprint 47
      duration: 2020-11-24..2020-11-07

  bugLabel: label:Bug # customize your bug label
  choreLabel: label:Chore # customize your chore label

  #android team query, can be customized
  storyQuery: is:issue is:closed assignee:?user closed:?sprint

server:
  port: 8013
