config:
  githubUrl: https://api.github.com/graphql # change if you use GH enterprise
  githubToken: xxx # GH personal access token

  userList: # GH username list
    - yyy
    - zzz

  sprintList: # define your sprints here
    - title: Sprint 43
      duration: 2020-09-15..2020-09-28
    - title: Sprint 44
      duration: 2020-09-29..2020-10-12
    - title: Sprint 45
      duration: 2020-10-13..2020-10-26
    - title: Sprint 46
      duration: 2020-10-27..2020-11-9

  bugLabel: label:Bug # customize your bug label
  choreLabel: label:Chore # customize your chore label
  storyQuery: is:issue is:closed assignee:?user closed:?sprint #android team query, can be customized
#  storyQuery: is:issue is:closed assignee:?user milestone:"Sprint 44" #when ?sprint excluded from query only 1 'sprint' should be included in sprintList

server:
  port: 8013
