config:
  githubUrl: https://api.github.com/graphql # change if you use GH enterprise
  githubToken: xxx # GH personal access token

  userList: # GH username list
    - andaeys
    - ayinozendy
    - denicahyawintaka
    - liauli
    - mcaras
    - leo0263
    - naufalazzaahid
    - wildhanstrdy

  sprintList: # define your sprints here
    - title: Sprint 44
      duration: 2020-09-29..2020-10-12
    - title: Sprint 45
      duration: 2020-10-13..2020-11-02
    - title: Sprint 46
      duration: 2020-11-03..2020-11-23
    - title: Sprint 47
      duration: 2020-11-24..2020-11-07
    - title: Sprint 48
      duration: 2020-12-08..2021-01-04
    - title: Sprint 49
      duration: 2021-01-13..2021-02-01
    - title: Sprint 50
      duration: 2021-02-02..2021-02-16
    - title: Sprint 51
      duration: 2021-02-16..2021-03-01
    - title: Sprint 52
      duration: 2021-03-02..2021-03-15
    - title: Sprint 53
      duration: 2021-03-16..2021-03-29

  #android team query, can be customized. For example, 'closed' can be replaced by 'created'
  storyQuery: is:issue is:closed assignee:?user closed:?sprint
  bugQuery: is:issue is:closed assignee:?user closed:?sprint label:Bug
  choreQuery: is:issue is:closed assignee:?user closed:?sprint label:Chore

server:
  port: 8013
